Traceback (most recent call last):
  File "/Users/rwegener/miniconda3/envs/sarp/lib/python3.13/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/Users/rwegener/miniconda3/envs/sarp/lib/python3.13/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/rwegener/miniconda3/envs/sarp/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/Users/rwegener/miniconda3/envs/sarp/lib/python3.13/asyncio/base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/Users/rwegener/miniconda3/envs/sarp/lib/python3.13/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "/Users/rwegener/miniconda3/envs/sarp/lib/python3.13/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/rwegener/miniconda3/envs/sarp/lib/python3.13/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Prepare the data
was_2020[(was_2020['n-Butane (E/B)'] < 0) | (was_2020['n-Butane (E/B)'] > 1000)]  = np.NaN
was_2020[(was_2020['i-Butane (E/B)'] < 0) | (was_2020['i-Butane (E/B)'] > 1000)]  = np.NaN
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[9], line 2[0m
[1;32m      1[0m [38;5;66;03m# Prepare the data[39;00m
[0;32m----> 2[0m was_2020[(was_2020[[38;5;124m'[39m[38;5;124mn-Butane (E/B)[39m[38;5;124m'[39m] [38;5;241m<[39m [38;5;241m0[39m) [38;5;241m|[39m (was_2020[[38;5;124m'[39m[38;5;124mn-Butane (E/B)[39m[38;5;124m'[39m] [38;5;241m>[39m [38;5;241m1000[39m)]  [38;5;241m=[39m [43mnp[49m[38;5;241;43m.[39;49m[43mNaN[49m
[1;32m      3[0m was_2020[(was_2020[[38;5;124m'[39m[38;5;124mi-Butane (E/B)[39m[38;5;124m'[39m] [38;5;241m<[39m [38;5;241m0[39m) [38;5;241m|[39m (was_2020[[38;5;124m'[39m[38;5;124mi-Butane (E/B)[39m[38;5;124m'[39m] [38;5;241m>[39m [38;5;241m1000[39m)]  [38;5;241m=[39m np[38;5;241m.[39mNaN

File [0;32m~/miniconda3/envs/sarp/lib/python3.13/site-packages/numpy/__init__.py:400[0m, in [0;36m__getattr__[0;34m(attr)[0m
[1;32m    397[0m     [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m(__former_attrs__[attr], name[38;5;241m=[39m[38;5;28;01mNone[39;00m)
[1;32m    399[0m [38;5;28;01mif[39;00m attr [38;5;129;01min[39;00m __expired_attributes__:
[0;32m--> 400[0m     [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m(
[1;32m    401[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124m`np.[39m[38;5;132;01m{[39;00mattr[38;5;132;01m}[39;00m[38;5;124m` was removed in the NumPy 2.0 release. [39m[38;5;124m"[39m
[1;32m    402[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00m__expired_attributes__[attr][38;5;132;01m}[39;00m[38;5;124m"[39m,
[1;32m    403[0m         name[38;5;241m=[39m[38;5;28;01mNone[39;00m
[1;32m    404[0m     )
[1;32m    406[0m [38;5;28;01mif[39;00m attr [38;5;241m==[39m [38;5;124m"[39m[38;5;124mchararray[39m[38;5;124m"[39m:
[1;32m    407[0m     warnings[38;5;241m.[39mwarn(
[1;32m    408[0m         [38;5;124m"[39m[38;5;124m`np.chararray` is deprecated and will be removed from [39m[38;5;124m"[39m
[1;32m    409[0m         [38;5;124m"[39m[38;5;124mthe main namespace in the future. Use an array with a string [39m[38;5;124m"[39m
[1;32m    410[0m         [38;5;124m"[39m[38;5;124mor bytes dtype instead.[39m[38;5;124m"[39m, [38;5;167;01mDeprecationWarning[39;00m, stacklevel[38;5;241m=[39m[38;5;241m2[39m)

[0;31mAttributeError[0m: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.

