Traceback (most recent call last):
  File "/Users/rwegener/miniconda3/envs/sarp/lib/python3.13/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/Users/rwegener/miniconda3/envs/sarp/lib/python3.13/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/rwegener/miniconda3/envs/sarp/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/Users/rwegener/miniconda3/envs/sarp/lib/python3.13/asyncio/base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/Users/rwegener/miniconda3/envs/sarp/lib/python3.13/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "/Users/rwegener/miniconda3/envs/sarp/lib/python3.13/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/rwegener/miniconda3/envs/sarp/lib/python3.13/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
aviris_ds = xr.open_dataset('./data/subset_f131205t01p00r10rdn_e_sc01_ort_img', engine='rasterio')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[3], line 1[0m
[0;32m----> 1[0m aviris_ds [38;5;241m=[39m [43mxr[49m[38;5;241;43m.[39;49m[43mopen_dataset[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43m./data/subset_f131205t01p00r10rdn_e_sc01_ort_img[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mengine[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mrasterio[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m~/miniconda3/envs/sarp/lib/python3.13/site-packages/xarray/backends/api.py:665[0m, in [0;36mopen_dataset[0;34m(filename_or_obj, engine, chunks, cache, decode_cf, mask_and_scale, decode_times, decode_timedelta, use_cftime, concat_characters, decode_coords, drop_variables, inline_array, chunked_array_type, from_array_kwargs, backend_kwargs, **kwargs)[0m
[1;32m    662[0m [38;5;28;01mif[39;00m from_array_kwargs [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    663[0m     from_array_kwargs [38;5;241m=[39m {}
[0;32m--> 665[0m backend [38;5;241m=[39m [43mplugins[49m[38;5;241;43m.[39;49m[43mget_backend[49m[43m([49m[43mengine[49m[43m)[49m
[1;32m    667[0m decoders [38;5;241m=[39m _resolve_decoders_kwargs(
[1;32m    668[0m     decode_cf,
[1;32m    669[0m     open_backend_dataset_parameters[38;5;241m=[39mbackend[38;5;241m.[39mopen_dataset_parameters,
[0;32m   (...)[0m
[1;32m    675[0m     decode_coords[38;5;241m=[39mdecode_coords,
[1;32m    676[0m )
[1;32m    678[0m overwrite_encoded_chunks [38;5;241m=[39m kwargs[38;5;241m.[39mpop([38;5;124m"[39m[38;5;124moverwrite_encoded_chunks[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m)

File [0;32m~/miniconda3/envs/sarp/lib/python3.13/site-packages/xarray/backends/plugins.py:202[0m, in [0;36mget_backend[0;34m(engine)[0m
[1;32m    200[0m     engines [38;5;241m=[39m list_engines()
[1;32m    201[0m     [38;5;28;01mif[39;00m engine [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m engines:
[0;32m--> 202[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    203[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;124munrecognized engine [39m[38;5;124m'[39m[38;5;132;01m{[39;00mengine[38;5;132;01m}[39;00m[38;5;124m'[39m[38;5;124m must be one of your download engines: [39m[38;5;132;01m{[39;00m[38;5;28mlist[39m(engines)[38;5;132;01m}[39;00m[38;5;124m. [39m[38;5;124m"[39m
[1;32m    204[0m             [38;5;124m"[39m[38;5;124mTo install additional dependencies, see:[39m[38;5;130;01m\n[39;00m[38;5;124m"[39m
[1;32m    205[0m             [38;5;124m"[39m[38;5;124mhttps://docs.xarray.dev/en/stable/user-guide/io.html [39m[38;5;130;01m\n[39;00m[38;5;124m"[39m
[1;32m    206[0m             [38;5;124m"[39m[38;5;124mhttps://docs.xarray.dev/en/stable/getting-started-guide/installing.html[39m[38;5;124m"[39m
[1;32m    207[0m         )
[1;32m    208[0m     backend [38;5;241m=[39m engines[engine]
[1;32m    209[0m [38;5;28;01melif[39;00m [38;5;28missubclass[39m(engine, BackendEntrypoint):

[0;31mValueError[0m: unrecognized engine 'rasterio' must be one of your download engines: ['netcdf4', 'scipy', 'store']. To install additional dependencies, see:
https://docs.xarray.dev/en/stable/user-guide/io.html 
https://docs.xarray.dev/en/stable/getting-started-guide/installing.html

